### ISSUE TITLE
Fast country name request

### ISSUE THREAD

**Issue by Dr-Hex** [maxmind/MaxMind-DB-Reader-dotnet#120]
Hi,
can you suggest please the most speed efficient way to access the country name info?

I'm using the following code:
```
                var ip = IPAddress.Parse(ip_address);
                var data = reader.Find<Dictionary<string, object>>(ip);

                if (data == null) return "";
                if (!data.ContainsKey("country")) return "";
                if (data["country"] == null) return "";

                Dictionary<string, object> country = (Dictionary<string, object>)data["country"];
                Dictionary<string, object> namesCountry = (Dictionary<string, object>)country["names"];

                if (namesCountry["en"] == null) return "";
                return namesCountry["en"].ToString();
```
Can we simplify something to be both fast and safe?

Also, perhaps, you may want to append your code snippet on the main page of the project (for ease of use by newcomers)?

**Comment by oschwald** [comment]
Most people should be using [`MaxMind.GeoIP2`](https://www.nuget.org/packages/MaxMind.GeoIP2) rather than this low-level reader directly. That said, it is possible to improve upon the performance of that package by constructing objects that only deserialize the data you want. However, deserializing to a dictionary like you do above will not show significant performance benefits over  `MaxMind.GeoIP2` as it still deserializes all of the data.
